version: '3.8'

# GitLab CE를 Docker Compose로 실행하는 설정
# 사용법: docker-compose -f docker-compose.gitlab.yml up -d

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: nas-gitlab
    restart: unless-stopped
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://YOUR_SERVER_IP'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # 메일 설정 (선택사항)
        # gitlab_rails['smtp_enable'] = true
        # gitlab_rails['smtp_address'] = "smtp.gmail.com"
        # gitlab_rails['smtp_port'] = 587
        # gitlab_rails['smtp_user_name'] = "your-email@gmail.com"
        # gitlab_rails['smtp_password'] = "your-password"
        # gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        # gitlab_rails['smtp_authentication'] = "login"
        # gitlab_rails['smtp_enable_starttls_auto'] = true
    ports:
      - "8080:80"      # HTTP (NAS 프론트엔드와 포트 충돌 방지)
      - "8443:443"     # HTTPS
      - "2222:22"      # SSH
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - nas-network
    # 리소스 제한 (선택사항)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # GitLab Runner (선택사항)
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: nas-gitlab-runner
    restart: unless-stopped
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nas-network
    # Runner는 GitLab에서 등록 토큰을 받아서 수동으로 등록해야 합니다
    # docker exec -it nas-gitlab-runner gitlab-runner register

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  nas-network:
    driver: bridge


